// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "male": "ذكر",
  "female": "أنثى",
  "boardingTitle1": "شخص تائه؟",
  "boardingTitle2": "تريد إرشاد؟",
  "boardingSubTitle1": "قم بالتبليغ عن الشخص التائه بسهولة",
  "boardingSubTitle2": "أحصل على جميع الإرشادات الخاصة بك",
  "skip": "تخطي",
  "chooseAccountType": "اختر صفة التسجيل",
  "moetmer": "معتمر",
  "hajji": "حاج",
  "loginNow": "دخول الآن",
  "userName": "اسم المستخدم",
  "password": "كلمة المرور",
  "notHaveAnAccount": "ليس لديك حساب؟ ",
  "registerNow": "سجل الآن",
  "signAsGuest": "الدخول كزائر",
  "FastCommunication": "التواصل السريع",
  "unifiedCommunications": "الاتصال الموحد",
  "communicationWhatsApp": "واتساب مرشد يحولك للدردشة مباشرة",
  "registerNewHajji": "تسجيل حاج جديد",
  "registerNewMoetamer": "تسجيل معتمر جديد",
  "arabicNamePassport": "الاسم بالكامل بالعربي حسب الجواز",
  "englishNamePassport": "الاسم بالكامل بالانجليزي حسب الجواز",
  "profilePic": "صورة شخصية",
  "phoneNumber": "رقم الجوال",
  "nationality": "الجنسية",
  "dateOfBirth": "تاريخ الميلاد",
  "email": "البريد الالكتروني",
  "passportNo": "رقم الجواز",
  "visaNo": "رقم التأشيرة",
  "boardNo": "رقم الحدود",
  "arriveDate": "تاريخ الوصول",
  "leaveDate": "تاريخ المغادرة",
  "residentialAddress": "مقر السكن",
  "mennaNo": "رقم المخيم (منى)",
  "arfaNo": "رقم المخيم (عرفة)",
  "mozdalefaNo": "رقم المخيم (مزدلفة)",
  "hotelAndCampsiteName": "اسم الفندق | المخيم",
  "officialMissionName": "اسم شركه العمره | الحملة",
  "edit": "تعديل",
  "haveDisability?": "هل تعاني من إعاقة؟",
  "agentName": "اسم الوكيل",
  "confirmPassword": "تأكيد كلمة المرور",
  "whenYouRegisterYouAgree": "القيام بالتسجيل فأنت توافق على",
  "privacyPolicy": "الشروط و الأحكام",
  "haveAccount": "لديك حساب؟ ",
  "maccaHotelName": "اسم الفندق في مكة المكرمة",
  "madinaHotelName": "اسم الفندق في المدينة المنورة",
  "welcomeToMorshed": "أهلًا بك في تطبيق مرشد لا تقلق نحن هنا لخدمتك",
  "reportingCaseOfMentalBreakdown": "تقديم بلاغ\nلحالة توهان",
  "videoCall": "طلب\n مرشد",
  "otherServices": "خدمات أخرى",
  "counselingOfficesAndCounselors": "مكاتب الإرشاد و المرشدين",
  "home": "الرئيسية",
  "notifications": "الإشعارات",
  "myBarcode": "باركودي",
  "myAccommodationAndTrips": "سكني ورحلاتي",
  "more": "المزيد",
  "myCard": "بطاقتي",
  "pleaseChooseType": "من فضلك اختار نوع الحساب",
  "Instructions": "إرشادات",
  "transports": "وسائل النقل",
  "salah": "الصلوات",
  "shopping": "التسوق والترفيه",
  "iLost": "أنا تائه",
  "anotherOneIsLost": "شخص اخر",
  "reporting": "تقديم بلاغ",
  "reportDetails": "تفاصيل البلاغ",
  "commentsAndAssistance": "ملاحظات | طريقة المساعدة",
  "reportLocation": "موقع البلاغ",
  "changeLocation": "تغيير الموقع",
  "WhatCanWeDoToAssistYou": "كيف يمكننا مساعدتك؟",
  "WhatCanWeDoToAssistHim": "كيف يمكننا مساعدته؟",
  "iWouldLikeHelpWithReachingTheHotel": "أود المساعدة للوصول إلى الفندق",
  "communicatingThroughVideoCall": "التواصل عبر الاتصال المرئي",
  "iWouldLikeHelpWithReachingTheCamp": "أود المساعدة للوصول إلى المخيم",
  "INeedHelpToJoinTheGroup": "أود المساعدة للألتحاق بالمجموعة",
  "findingInformationByScanningQrCode": "البحث بالباركود",
  "findingInformationUsingPassportNumber": "البحث  برقم الجواز",
  "findingInformationUsingId": "البحث  بالرقم التسلسلي",
  "findingInformationUsingHotelName": "البحث  باسم الفندق",
  "findingInformationUsingVisaNumber": "البحث  برقم التأشيرة",
  "country": "الدوله",
  "sex": "الجنس",
  "search": "بحث",
  "scanQrCode": "مسح الباركود",
  "moetamerInfo": "بيانات المعتمر",
  "age": "السن",
  "hajjiInfo": "بيانات الحاج",
  "yourComplaintHasBeenReceivedSuccessfully": "تم تقديم بلاغك بنجاح",
  "subTitleOfReceivedComplaintSuccessfully": "سوف يتم اتخاذ الإجراءات المناسبة سريعًا فقط ابقى متصلًا ريثما يتم التواصل معك",
  "findingInfoByNamePHoneOrLang": "البحث  بالاسم أو رقم الجوال أو اللغة",
  "SorryYouMustSubscribe": "عفوًا الخدمة تتطلب الاشتراك",
  "moveToPaymentScreen": "الانتقال إلى صفحة الدفع",
  "technicalSupport": "الدعم الفني",
  "sendMessage": "أرسل رسالة",
  "provideYourCodeToAssistYou": "قم بإظهار رمز الكود الخاص بك لأي مرشد أو مكتب إرشادي لمساعدتك",
  "ServicesOfTheTwoHolyMosques": "خدمات الحرمين الشريفين",
  "umrahAndHajjInformation": "معلومات العمرة و الحج",
  "GuidebookForLostPersons": "دليل التوهان",
  "aboutMorshed": "عن مرشد",
  "touristAttractions": "المزارات السياحية",
  "maccaTransports": "حافلات مكة",
  "carPark": "موقف السيارات\n العامة",
  "haramainTrain": "قطار الحرمين",
  "mashaerTrain": "قطار المشاعر",
  "taxi": "تكاسي الأجرة",
  "PaidCarParks": "مواقف السيارات\nالمدفوعة",
  "subscription": "الاشتراك",
  "theSubscriptionPackage": "أنت الآن مشترك في باقة ال3 شهور",
  "numberOfReportsYouHaveMade": "عدد مرات الإبلاغ التي قمت بها :",
  "availableNumberOfReports": "عدد مرات الإبلاغ المتاحة :",
  "unlimitedDuringSubscription": "مفتوح مدة الاشتراك",
  "renewSubscription": "تجديد الاشتراك",
  "cancelSubscription": "الغاء الاشتراك",
  "searchForGuidanceOffices": "بحث عن مكتب الإرشاد",
  "guidanceOffices": "مكاتب الإرشاد",
  "guides": "المرشدين",
  "myReports": "بلاغاتي",
  "underProcessing": "تحت المعالجة",
  "guideOnTheWay": "المرشد في الطريق",
  "Resolved": "تمت المعالجة",
  "reportNumber": "رقم البلاغ",
  "cancelReport": "إلغاء البلاغ",
  "doYouWantDeleteAccount": "هل تريد حذف الحساب؟",
  "yes": "نعم",
  "no": "لا شكرا",
  "contactUs": "تواصل معنا",
  "contactViaWhatsApp": "تواصل معنا عبر واتساب",
  "contactViaEmail": "تواصل معنا عبر البريد الالكتروني",
  "weArePleasedToAnswerYourInquiry": "يسرنا الإجابة عن استفسارك",
  "writeHere": "اكتب هنا",
  "settings": "الإعدادات",
  "deleteAccount": " حذف الحساب",
  "language": "اللغة",
  "logOut": "تسجيل خروج",
  "profile": "الحساب",
  "Companions": "المرافقين",
  "sendInquiry": "إرسال استفسار",
  "errorWhileMovingToEmail": "حذث خطأ اثناء الإنتقال الي الإيميل",
  "errorWhileMovingToWhatsApp": "حذث خطأ اثناء الإنتقال الي الواتس اب",
  "shareMorshed": "شارك مرشد",
  "morshedSubscription": "إشتراك مرشد",
  "passportIdResidencePermitNumber": "رقم الجواز | الهوية | الإقامة",
  "add": "إضافة",
  "addCompanion": "إضافة مرافق",
  "YouMustLoginFirst": "يجب عليك تسجيل الدخول أولا",
  "disabilityType": "نوع الإعاقه",
  "press_here": "أضغط هنا",
  "menna_loc": "عنوان موقع منى",
  "arafa_loc": "عنوان موقع عرفه",
  "mozdalifa_loc": "عنوان موقع المزدلفه",
  "macca_hotel_loc": "موقع القندق في مكه المكرمه",
  "madina_hotel_loc": "موقع القندق في المدينه المنوره",
  "service_under_development": "الخدمه مازالت تحت التطوير",
  "office_search": "بحث عن مكتب إرشاد",
  "office_guide": "مكاتب إرشاد",
  "guide_service_provider": "مقدمي خدمات إرشاد",
  "companions_not_fount": "لا يوجد لديك مرافقين حتى الآن",
  "search_by_name": "البحث عن طريق الأسم",
  "please_write_companions": "من فضلك أدخل اسم المرافق",
  "no_reports": "لا يوجد لديك بلاغات",
  "report_no": "رقم البلاغ:",
  "note_for_report": "ملاحظات البلاغ عن الشخص التائه يمكنك\n تقديم البلاغ بسهوله",
  "companions_Added_Successfully": "تم اضافه المرافق بنجاح",
  "please_verify_date": "برجاء التأكد من البيانات المدخله",
  "enter_date_of_birth": "من فضلك أدخل تاريخ الميلاد",
  "enter_id": "من فضلك أدخل رقم جواز السفر أو رقم الإقامه",
  "enter_office_name_for_search": "من فضلك أدخل أسم المكتب الذي تود البحث عنه",
  "no_notifications": "لا يوجد لديك إشعارات",
  "error": "حدث خطأ",
  "no_internet_connection": "لا يوجد اتصال بالانترنت",
  "retry": "اعاده المحاوله",
  "profile_update_successfully": "تم تحديث ملفك الشخصي بنجاح",
  "error_occurred": "حدث خطأ أثناء الأتصال بالسيرفر",
  "logout_fail": "فشل في تسجيل الخروج",
  "hearing_disability": "سمعيه",
  "motor_and_physical_disabilities": "جسميه وحركيه",
  "mental_disabilities": "عقليه",
  "visual_disability": "بصريه",
  "no_office_found": "لا يوجد مكتب إرشاد بهذا الأسم",
  "report_upload_successfully": "تم رفع بلاغك بنجاح سيتم التواصل معك قريبا",
  "report_failed_uploaded": "حدث خطأ أثناء رفع بلاغك برجاء المحاوله في مره اخرى",
  "id_not_found": "الرقم التسلسلي غير موجود",
  "phone_not_found": "رقم الجوال غير موجود",
  "visa_not_found": "رقم التأشيرة غير موجود",
  "passport_not_found": "رقم الجواز غير موجود",
  "border_not_found": "رقم الحدود غير موجود",
  "enter_user_name": "برجاء ادخال اسم المستخدم",
  "enter_password": "برجاء ادخال الرقم السري",
  "enter_Full_arabic_name": "برجاء ادخال الاسم كامل بالعربي",
  "enter_Full_english_name": "برجاء ادخال الاسم كامل بالانجليزية",
  "choose_please": "برجاء الأختيار",
  "camera": "كاميرا",
  "gallery": "معرض الصور",
  "enter_phone_number": "أدخل رقم الجوال",
  "enter_user_name_correctly": "من فضلك أدخل أسم المستخدم بصوره صحيحه",
  "enter_Passport_number": "أدخل رقم جواز سفرك",
  "enter_vise_no": "أدخل رقم التأشيرة",
  "enter_borderOrIdOrIqama_no": "رقم الحدود | الإقامة | الهويه الوطنية",
  "enter_arrival_date": "أدخل تاريخ الوصول",
  "enter_depurate_date": "أدخل تاريخ المغادره",
  "enter_makka_hotel": "اسم الفندق في مكه المكرمه",
  "madina_hotels_name": "اسم الفندق في المدينه المنوره",
  "report_loc": "تحديد موقع البلاغ",
  "finidingInfoByPhone": "البحث عن طريق رقم الجوال",
  "finidingInfoByBorderNo": "البحث عن طريق رقم الحدود",
  "no_service_provider": "لا يوجد مقدمي خدمات إرشاد",
  "no_company_found": "لا يوجد أسم شركه"
};
static const Map<String,dynamic> en = {
  "male": "Male",
  "female": "Female",
  "boardingTitle1": "Lost person?",
  "boardingTitle2": "Do you need guidance?",
  "boardingSubTitle1": "Report the lost person easily",
  "boardingSubTitle2": "Get all your instructions",
  "skip": "Skip",
  "chooseAccountType": "choose account type",
  "moetmer": "Pilgrim",
  "hajji": "Hajji",
  "loginNow": "Login now",
  "userName": "User name",
  "password": "password",
  "notHaveAnAccount": "Don't you have an account? ",
  "registerNow": "Register now",
  "signAsGuest": "Sing as guest",
  "FastCommunication": "Fast Communication",
  "unifiedCommunications": "Unified Communications",
  "communicationWhatsApp": "WhatsApp morshed redirects you to live chat",
  "registerNewHajji": "Register new hajji",
  "registerNewMoetamer": "Register new pilgrim",
  "edit": "Edit",
  "sendInquiry": "Send inquiry",
  "arabicNamePassport": "Full name in Arabic as per passport",
  "englishNamePassport": "Full name in English as per passport",
  "profilePic": "Personal photo",
  "phoneNumber": "Mobile phone number",
  "nationality": "Nationality",
  "dateOfBirth": "Date of birth",
  "email": "Email",
  "passportNo": "Passport No.",
  "visaNo": "Visa No.",
  "boardNo": "Border crossing number",
  "arriveDate": "Arrival date",
  "leaveDate": "Departure date",
  "residentialAddress": "Residential address",
  "mennaNo": "Mina camp number",
  "arfaNo": "Arafa camp number",
  "mozdalefaNo": "Muzdalifah camp number",
  "hotelAndCampsiteName": "Hotel | Camp name",
  "officialMissionName": "Official delegation | Expedition name",
  "haveDisability?": "Do you have a disability?",
  "agentName": "Agent name",
  "confirmPassword": "Confirm password",
  "whenYouRegisterYouAgree": "By registering, you agree to ",
  "privacyPolicy": "Privacy&Policy",
  "haveAccount": "Do you have an account? ",
  "maccaHotelName": "Hotel name in Mecca",
  "madinaHotelName": "Hotel name in Medina",
  "welcomeToMorshed": "Welcome to the Morshed app. Don't worry, we're here to serve you",
  "reportingCaseOfMentalBreakdown": "Report a case \n of disorientation",
  "videoCall": "Video\n call",
  "otherServices": "Other services",
  "counselingOfficesAndCounselors": "Counseling and guidance offices",
  "home": "Home",
  "notifications": "Notifications",
  "myBarcode": "My qrcode",
  "myAccommodationAndTrips": "My accommodation and travels",
  "more": "more",
  "myCard": "My card",
  "pleaseChooseType": "Please select the account type",
  "Instructions": "Instructions",
  "transports": "Transportation",
  "salah": "Salah",
  "shopping": "Shopping and entertainment",
  "iLost": "I'm lost",
  "anotherOneIsLost": "Another person",
  "reporting": "Filing a report",
  "reportDetails": "Report details",
  "commentsAndAssistance": "Comments | Help approach",
  "reportLocation": "Report location",
  "changeLocation": "Change Location",
  "WhatCanWeDoToAssistYou": "How can we assist you?",
  "WhatCanWeDoToAssistHim": "How can we assist him?",
  "iWouldLikeHelpWithReachingTheHotel": "I need assistance in getting to the hotel",
  "communicatingThroughVideoCall": "Communicating through video call",
  "iWouldLikeHelpWithReachingTheCamp": "I need assistance in getting to the camp",
  "INeedHelpToJoinTheGroup": "I need help in joining the group",
  "findingInformationByScanningQrCode": "Finding information by scanning qrcode",
  "findingInformationUsingPassportNumber": "Finding information using passport no.",
  "findingInformationUsingId": "Finding information using id",
  "findingInformationUsingHotelName": "Finding information using hotel name",
  "findingInformationUsingVisaNumber": "Finding information using Visa no.",
  "country": "Country",
  "sex": "Sex",
  "search": "Search",
  "scanQrCode": "Scan qrcode",
  "moetamerInfo": "Pilgrim's information",
  "hajjiInfo": "Hajj's information",
  "yourComplaintHasBeenReceivedSuccessfully": "Your report has been submitted successfully",
  "subTitleOfReceivedComplaintSuccessfully": "We will act quickly and appropriately. Please stay connected while we contact you",
  "findingInfoByNamePHoneOrLang": "Search by name, phone number, or language",
  "SorryYouMustSubscribe": "Sorry, the service requires a subscription",
  "moveToPaymentScreen": "Proceed to payment page",
  "technicalSupport": "Technical support",
  "sendMessage": "Send message",
  "provideYourCodeToAssistYou": "Show your qrcode to any counselor or guidance office for help",
  "ServicesOfTheTwoHolyMosques": "Services of the Two Holy Mosques",
  "umrahAndHajjInformation": "Umrah and Hajj information",
  "GuidebookForLostPersons": "Guidebook for lost persons",
  "aboutMorshed": "About morshed",
  "touristAttractions": "Tourist attractions",
  "maccaTransports": "Makkah buses",
  "carPark": "Public car \n park",
  "haramainTrain": "Haramain train",
  "mashaerTrain": "Mashaer train",
  "taxi": "Taxi",
  "PaidCarParks": "Paid car \n parks",
  "subscription": "Subscription",
  "theSubscriptionPackage": "You are now subscribed to the 3-month package",
  "numberOfReportsYouHaveMade": "Number of reports you have made :",
  "availableNumberOfReports": "Available report count :",
  "unlimitedDuringSubscription": "Unlimited during subscription ",
  "renewSubscription": "Renew subscription",
  "cancelSubscription": "Cancel subscription",
  "searchForGuidanceOffices": "Search for guidance offices",
  "guidanceOffices": "Guidance offices",
  "guides": "Guides",
  "myReports": "My reports",
  "underProcessing": "Under processing",
  "guideOnTheWay": "Guide on the way",
  "Resolved": "Resolved",
  "reportNumber": "reportNumber",
  "cancelReport": "Cancel report",
  "doYouWantDeleteAccount": "Are you sure you want to delete your account?",
  "yes": "yes",
  "no": "No, thanks",
  "contactUs": "Contact us",
  "contactViaWhatsApp": "Contact us via WhatsApp",
  "contactViaEmail": "Contact us via email",
  "weArePleasedToAnswerYourInquiry": "We are pleased to answer your inquiry",
  "writeHere": "Write here",
  "settings": "Settings",
  "deleteAccount": "Delete account",
  "language": "Language",
  "logOut": "Logout",
  "profile": "Profile",
  "Companions": "Companions",
  "shareMorshed": "Share morshed",
  "morshedSubscription": "Morshed subscription",
  "addCompanions": "Add companions",
  "passportIdResidencePermitNumber": "Passport | ID | Residence Number",
  "add": "Add",
  "YouMustLoginFirst": "Access requires login",
  "errorWhileMovingToEmail": "There was an error while moving to Email",
  "errorWhileMovingToWhatsApp": "There was an error while moving to WhatsApp",
  "age": "age",
  "addCompanion": "Add companion",
  "disabilityType": "Disability type",
  "press_here": "Press Here",
  "menna_loc": "Menna Location",
  "arafa_loc": "Arafat Location",
  "mozdalifa_loc": "Mozdalifa Location",
  "macca_hotel_loc": "Makka Hotel's Location",
  "madina_hotel_loc": "Madina Hotel's Location",
  "service_under_development": "This service under development",
  "office_search": "search offices",
  "office_guide": "Guide's Offices",
  "guide_service_provider": "Guide Service's Provider",
  "companions_not_fount": "there is no Companions Found",
  "search_by_name": "Search by name",
  "please_write_companions": "Please write name",
  "no_reports": "There is no reports found",
  "report_no": "Report No:",
  "note_for_report": "Notes you can upload report for lost person normally",
  "companions_Added_Successfully": "Companions Added Successfully",
  "please_verify_date": "Please verify The Date",
  "enter_date_of_birth": "Please enter your date of birth",
  "enter_id": "Please enter passport no. or Id Residence",
  "enter_office_name_for_search": "Please enter office name to we can search for you",
  "no_notifications": "No Notification Found",
  "error": "An Error Occurred",
  "no_internet_connection": "No Internet Connection",
  "retry": "Retry",
  "error_occurred": "There is an Error Occurred",
  "profile_update_successfully": "Profile Updated Successfully",
  "logout_fail": "error occurred while logout",
  "hearing_disability": "Hearing Disability",
  "motor_and_physical_disabilities": "Motor and physical Disabilities",
  "mental_disabilities": "Mental Disabilities",
  "visual_disability": "Visual Disability",
  "no_office_found": "There is no office by this name",
  "report_upload_successfully": "Your report uploaded successfully and we contact with you soon",
  "report_failed_uploaded": "Your report failed to upload please try again later",
  "id_not_found": "Id not Found",
  "phone_not_found": "Phone Number not Found",
  "visa_not_found": "Visa Number not found",
  "passport_not_found": "Passport Number not Found",
  "border_not_found": "Border Number not Found",
  "enter_user_name": "Enter User name",
  "enter_password": "Enter Password",
  "enter_Full_arabic_name": "Enter Full Arabic Name",
  "enter_Full_english_name": "Enter Full English Name",
  "choose_please": "Choose Please",
  "camera": "Camera",
  "gallery": "Gallery",
  "enter_phone_number": "Enter Phone Number",
  "enter_user_name_correctly": "Enter UserName Correctly",
  "enter_Passport_number": "Enter Passport Number",
  "enter_vise_no": "Enter Visa No",
  "enter_borderOrIdOrIqama_no": "Border No | ID No | Iqama No",
  "enter_arrival_date": "Enter Arrival Date",
  "enter_depurate_date": "Enter Leave Date",
  "enter_makka_hotel": "Makka Hotel Name",
  "madina_hotels_name": "Madina Hotel Name",
  "report_loc": "Report Location",
  "finidingInfoByPhone": "Search By Using Phone Number",
  "finidingInfoByBorderNo": "Search By Using Border Number",
  "no_service_provider": "There is no Service's Provider Found",
  "no_company_found": "No Company Found"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
